CAREER_SKILLS = {"Solo": ["Combat Sense", 
                          "Awareness/Notice", 
                          "Handgun", 
                          "Brawling", 
                          "Martial Arts", 
                          "Melee", 
                          "Weapon Tech", 
                          "Rifle", 
                          "Athletics", 
                          "Submachinegun", 
                          "Stealth"], 
                "Nomad": ["Family", 
                          "Awareness/Notice", 
                          "Endurance", 
                          "Melee", 
                          "Rifle", 
                          "Drive", 
                          "Basic Tech", 
                          "Wilderness Survival", 
                          "Brawling", 
                          "Athletics"], 
                "Rockerboy": ["Charismatic Leadership", 
                              "Awareness/Notice", 
                              "Perform", 
                              "Wardrobe & Style", 
                              "Composition", 
                              "Brawling", 
                              "Play Instrument", 
                              "Streetwise", 
                              "Persuasion", 
                              "Seduction", 
                              "Persuasion", 
                              "Seduction"], 
                "Corporate": ["Resources", 
                              "Awareness/Notice", 
                              "Human Perception", 
                              "Education", 
                              "Library Search", 
                              "Social", 
                              "Persuasion", 
                              "Stock Market", 
                              "Wardrobe & Style", 
                              "Personal Grooming"], 
                "Techie": ["Jury Rig", 
                           "Awareness/Notice", 
                           "Basic Tech", 
                           "Cybertech", 
                           "Teaching", 
                           "Education", 
                           "Electronics", 
                           "Gyro Tech", 
                           "Aero Tech", 
                           "Weapons Tech", 
                           "Electronic Security"], 
                "Med Tech": ["Medical Tech", 
                             "Awareness/Notice", 
                             "Basic Tech", 
                             "Diagnose", 
                             "Education", 
                             "Cryotank Operation", 
                             "Library Search", 
                             "Pharmaceuticals", 
                             "Zoology", 
                             "Human Perception"], 
                "Media": ["Credibility", 
                          "Awareness/Notice", 
                          "Composition", 
                          "Education", 
                          "Persuasion", 
                          "Human Perception", 
                          "Social", 
                          "Streetwise", 
                          "Photo & Film", 
                          "Interview"], 
                "Cop": ["Authority", 
                        "Awareness/Notice", 
                        "Handgun", 
                        "Human Perception", 
                        "Athletics", 
                        "Education", 
                        "Brawling", 
                        "Melee", 
                        "Interrogation", 
                        "Streetwise"], 
                "Fixer": ["Streetdeal", 
                          "Awareness/Notice", 
                          "Forgery", 
                          "Handgun", 
                          "Brawling", 
                          "Melee", 
                          "Pick Lock", 
                          "Pick Pocket", 
                          "Intimidate", 
                          "Persuasion"]}
                
CAREER = ["Combat Sense", 
          "Authority", 
          "Charismatic Leadership", 
          "Credibility", 
          "Family", 
          "Jury Rig", 
          "Medical Tech", 
          "Resources", 
          "Streetdeal"]
                
ATTR = ["Personal Grooming", 
        "Wardrobe & Style"]

BODY = ["Endurance", 
        "Strength Feat", 
        "Swimming"]

COOL = ["Interrogation", 
        "Intimidate", 
        "Oroatory", 
        "Resist Torture/Drugs", 
        "Streetwise"]

EMPATHY = ["Human Perception", 
           "Interview", 
           "Leadership", 
           "Seduction", 
           "Social", 
           "Persuasion", 
           "Perform"]

INT = ["Accounting", 
       "Anthropology", 
       "Awareness/Notice", 
       "Biology", 
       "Botany", 
       "Chemistry", 
       "Composition", 
       "Diagnose Illness", 
       "Education", 
       "Expert", 
       "Gamble", 
       "Geology", 
       "Hide/Evade", 
       "History", 
       "Language", 
       "Library Search", 
       "Mathematics", 
       "Physics", 
       "Programming", 
       "Shadow/Track", 
       "Stock Market", 
       "System Knowledge", 
       "Teaching", 
       "Wilderness Survival", 
       "Zoology"]

REF = ["Archery", 
       "Athletics", 
       "Brawling", 
       "Dance", 
       "Dodge & Escape", 
       "Driving", 
       "Fencing", 
       "Handgun", 
       "Heavy Weapons", 
       "Martial Arts", 
       "Melee", 
       "Motorcycle", 
       "Heavy Machinery", 
       "Pilot (Gyro)", 
       "Pilot (Fixed Wing)", 
       "Pilot (Dirigible)", 
       "Pilot (Vect. Thrust)", 
       "Rifle", 
       "Stealth", 
       "Submachinegun"]

TECH = ["Aero Tech", 
        "AV Tech", 
        "Basic Tech", 
        "Cryotank Operation", 
        "Cyberdeck Design", 
        "Cybertech", 
        "Demolitions", 
        "Disguise", 
        "Electronics", 
        "Electronic Security", 
        "First Aid", 
        "Forgery", 
        "Gyro Tech", 
        "Paint/Draw", 
        "Photo & Film", 
        "Pharmaceuticals", 
        "Pick Lock", 
        "Pick Pocket", 
        "Play Instrument", 
        "Weaponsmith"]

SKILLS = {"ATTR": ATTR, 
          "BODY": BODY, 
          "COOL": COOL, 
          "EMP": EMPATHY, 
          "INT": INT, 
          "REF": REF, 
          "TECH": TECH}